export type BusinessPreset = {
  id: string
  name: string
  description: string
  revenue: number
  costOfGoods: number
  operatingExpenses: number
}

export const BUSINESS_PRESETS: BusinessPreset[] = [
  {
    id: "tea-stall",
    name: "Tea Stall",
    description: "Small roadside tea stall with steady daily footfall.",
    revenue: 90000,
    costOfGoods: 35000,
    operatingExpenses: 20000,
  },
  {
    id: "biryani-shop",
    name: "Biryani Shop",
    description: "Quick service biryani outlet in a busy locality.",
    revenue: 180000,
    costOfGoods: 90000,
    operatingExpenses: 40000,
  },
  {
    id: "grocery-store",
    name: "Grocery Store",
    description: "Neighbourhood kirana with mixed product margins.",
    revenue: 250000,
    costOfGoods: 170000,
    operatingExpenses: 50000,
  },
  {
    id: "salon",
    name: "Salon",
    description: "Unisex salon with 3–4 chairs and walk‑in customers.",
    revenue: 140000,
    costOfGoods: 30000,
    operatingExpenses: 55000,
  },
  {
    id: "gym",
    name: "Gym / Fitness Studio",
    description: "Subscription based gym with monthly memberships.",
    revenue: 220000,
    costOfGoods: 40000,
    operatingExpenses: 90000,
  },
  {
    id: "cloud-kitchen",
    name: "Cloud Kitchen",
    description: "Delivery‑only kitchen on Swiggy/Zomato.",
    revenue: 260000,
    costOfGoods: 140000,
    operatingExpenses: 70000,
  },
  {
    id: "tuition-center",
    name: "Tuition Center",
    description: "After‑school tuition center with multiple batches.",
    revenue: 120000,
    costOfGoods: 15000,
    operatingExpenses: 50000,
  },
  {
    id: "mobile-shop",
    name: "Mobile Shop",
    description: "Phone and accessories store with inventory costs.",
    revenue: 300000,
    costOfGoods: 230000,
    operatingExpenses: 60000,
  },
  {
    id: "car-wash",
    name: "Car Wash",
    description: "Car wash bay with daily repeat customers.",
    revenue: 110000,
    costOfGoods: 25000,
    operatingExpenses: 40000,
  },
  {
    id: "bakery",
    name: "Bakery",
    description: "Local bakery selling bread, cakes and snacks.",
    revenue: 190000,
    costOfGoods: 100000,
    operatingExpenses: 55000,
  },
  {
    id: "pharmacy",
    name: "Pharmacy / Medical Store",
    description: "Retail medical shop with prescription and OTC sales.",
    revenue: 320000,
    costOfGoods: 240000,
    operatingExpenses: 70000,
  },
  {
    id: "restaurant",
    name: "Family Restaurant",
    description: "Casual dining restaurant with 40–50 covers.",
    revenue: 400000,
    costOfGoods: 210000,
    operatingExpenses: 130000,
  },
  {
    id: "street-food-cart",
    name: "Street Food Cart",
    description: "Popular evening chaat or momo cart.",
    revenue: 80000,
    costOfGoods: 35000,
    operatingExpenses: 20000,
  },
  {
    id: "coaching-center",
    name: "Coaching Center",
    description: "Competitive exam coaching with batch‑wise fees.",
    revenue: 260000,
    costOfGoods: 30000,
    operatingExpenses: 110000,
  },
  {
    id: "play-school",
    name: "Play School",
    description: "Pre‑school / daycare with monthly fees.",
    revenue: 210000,
    costOfGoods: 40000,
    operatingExpenses: 110000,
  },
  {
    id: "garment-store",
    name: "Garment Store",
    description: "Clothing and fashion store in a local market.",
    revenue: 280000,
    costOfGoods: 190000,
    operatingExpenses: 65000,
  },
  {
    id: "hardware-store",
    name: "Hardware Store",
    description: "Building material and hardware shop.",
    revenue: 300000,
    costOfGoods: 215000,
    operatingExpenses: 60000,
  },
  {
    id: "stationery-shop",
    name: "Stationery Shop",
    description: "Stationery and printing shop near schools/offices.",
    revenue: 120000,
    costOfGoods: 65000,
    operatingExpenses: 30000,
  },
  {
    id: "photo-studio",
    name: "Photo Studio",
    description: "Photo print and studio services.",
    revenue: 90000,
    costOfGoods: 20000,
    operatingExpenses: 35000,
  },
  {
    id: "cyber-cafe",
    name: "Cyber Cafe",
    description: "Internet, printing and basic computer services.",
    revenue: 70000,
    costOfGoods: 15000,
    operatingExpenses: 30000,
  },
  {
    id: "laundry",
    name: "Laundry / Dry Cleaners",
    description: "Per‑kg laundry and dry cleaning service.",
    revenue: 130000,
    costOfGoods: 30000,
    operatingExpenses: 50000,
  },
  {
    id: "dairy-shop",
    name: "Dairy Shop",
    description: "Milk, curd and dairy products outlet.",
    revenue: 150000,
    costOfGoods: 110000,
    operatingExpenses: 25000,
  },
  {
    id: "florist",
    name: "Florist",
    description: "Flower shop for daily and event orders.",
    revenue: 90000,
    costOfGoods: 45000,
    operatingExpenses: 25000,
  },
  {
    id: "bookstore",
    name: "Bookstore",
    description: "Academic and general books with seasonal peaks.",
    revenue: 160000,
    costOfGoods: 100000,
    operatingExpenses: 40000,
  },
  {
    id: "printing-press",
    name: "Printing Press",
    description: "Digital printing jobs and visiting cards.",
    revenue: 180000,
    costOfGoods: 90000,
    operatingExpenses: 50000,
  },
  {
    id: "cafe",
    name: "Cafe",
    description: "Coffee and snacks cafe with young crowd.",
    revenue: 200000,
    costOfGoods: 90000,
    operatingExpenses: 75000,
  },
  {
    id: "toy-store",
    name: "Toy Store",
    description: "Retail toy shop with festival spikes.",
    revenue: 140000,
    costOfGoods: 90000,
    operatingExpenses: 35000,
  },
  {
    id: "pet-shop",
    name: "Pet Shop",
    description: "Pet food, accessories and basic grooming.",
    revenue: 130000,
    costOfGoods: 75000,
    operatingExpenses: 35000,
  },
  {
    id: "auto-garage",
    name: "Auto Garage",
    description: "Two‑wheeler or car repair garage.",
    revenue: 160000,
    costOfGoods: 60000,
    operatingExpenses: 60000,
  },
  {
    id: "logistics-agent",
    name: "Courier / Logistics Agent",
    description: "Local logistics and courier agency.",
    revenue: 180000,
    costOfGoods: 100000,
    operatingExpenses: 50000,
  },
  {
    id: "event-planner",
    name: "Event Planner",
    description: "Event planning with vendor coordination.",
    revenue: 250000,
    costOfGoods: 120000,
    operatingExpenses: 80000,
  },
  {
    id: "wedding-hall",
    name: "Wedding Hall",
    description: "Banquet hall with seasonal bookings.",
    revenue: 500000,
    costOfGoods: 220000,
    operatingExpenses: 200000,
  },
  {
    id: "cloud-retail",
    name: "Online Store",
    description: "E‑commerce store with shipping and returns.",
    revenue: 280000,
    costOfGoods: 170000,
    operatingExpenses: 80000,
  },
  {
    id: "tiffin-service",
    name: "Tiffin Service",
    description: "Home‑cooked tiffin subscriptions.",
    revenue: 100000,
    costOfGoods: 50000,
    operatingExpenses: 30000,
  },
  {
    id: "photography-freelance",
    name: "Freelance Photographer",
    description: "Event and portfolio photography gigs.",
    revenue: 150000,
    costOfGoods: 30000,
    operatingExpenses: 60000,
  },
  {
    id: "freelance-designer",
    name: "Freelance Designer",
    description: "Branding and design projects.",
    revenue: 120000,
    costOfGoods: 15000,
    operatingExpenses: 45000,
  },
  {
    id: "freelance-developer",
    name: "Freelance Developer",
    description: "Web / app development projects.",
    revenue: 180000,
    costOfGoods: 20000,
    operatingExpenses: 60000,
  },
  {
    id: "coworking-space",
    name: "Coworking Space",
    description: "Shared office space with hot desks.",
    revenue: 320000,
    costOfGoods: 80000,
    operatingExpenses: 150000,
  },
  {
    id: "hostel",
    name: "Hostel / PG",
    description: "Student/working professional hostel with beds.",
    revenue: 280000,
    costOfGoods: 90000,
    operatingExpenses: 130000,
  },
  {
    id: "homestay",
    name: "Homestay",
    description: "Tourist homestay with seasonal occupancy.",
    revenue: 180000,
    costOfGoods: 60000,
    operatingExpenses: 80000,
  },
  {
    id: "solar-installer",
    name: "Solar Installer",
    description: "Residential and small commercial solar projects.",
    revenue: 350000,
    costOfGoods: 220000,
    operatingExpenses: 90000,
  },
  {
    id: "organic-store",
    name: "Organic Store",
    description: "Organic groceries and wellness products.",
    revenue: 190000,
    costOfGoods: 120000,
    operatingExpenses: 45000,
  },
  {
    id: "water-plant",
    name: "Packaged Water Plant",
    description: "20L water cans and bottled water.",
    revenue: 210000,
    costOfGoods: 110000,
    operatingExpenses: 70000,
  },
  {
    id: "agri-trader",
    name: "Agri Trader",
    description: "Buying from farmers and selling to markets.",
    revenue: 400000,
    costOfGoods: 320000,
    operatingExpenses: 50000,
  },
  {
    id: "clinic",
    name: "Clinic",
    description: "Doctor clinic with consultation fees.",
    revenue: 220000,
    costOfGoods: 40000,
    operatingExpenses: 90000,
  },
  {
    id: "diagnostic-center",
    name: "Diagnostic Center",
    description: "Pathology and scanning services.",
    revenue: 300000,
    costOfGoods: 120000,
    operatingExpenses: 120000,
  },
  {
    id: "spa",
    name: "Spa",
    description: "Wellness spa with appointment‑based services.",
    revenue: 200000,
    costOfGoods: 70000,
    operatingExpenses: 90000,
  },
  {
    id: "salon-franchise",
    name: "Salon Franchise",
    description: "Franchise salon with royalty fees.",
    revenue: 260000,
    costOfGoods: 80000,
    operatingExpenses: 130000,
  },
  {
    id: "coaching-franchise",
    name: "Coaching Franchise",
    description: "Franchise coaching center in a tier‑2 city.",
    revenue: 300000,
    costOfGoods: 60000,
    operatingExpenses: 150000,
  },
]

